### ISSUE TITLE
Usersnap Feedback - For all entry forms - provide a link to the guidelines as part of this info bar.

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1125]
**Sender**: jesi.carson@gmail.com
**Comment**: For all entry forms - provide a link to the guidelines as part of this info bar.
[Open #814 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/814)

<a href='https://usersnappublic.s3.amazonaws.com/2020-08-26/22-59/65b2d3e4-5310-4b07-bce3-857fe8878edc.png'>![Usersnap Feedback - For all entry forms - provide a link to the guidelines as part of this info bar.](https://usersnappublic.s3.amazonaws.com/2020-08-26/22-59/0835877f-1263-45ec-91cf-83fd6275d8a4.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-08-26/22-59/65b2d3e4-5310-4b07-bce3-857fe8878edc.png'>Download original image</a>

**Browser**: Chrome 84 (Macintosh)
**Referer**: [https://participedia.net/case/new](https://participedia.net/case/new)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Suggested update to the prompt text for cases, as an example:

> This is the quick/short form and only contains a subset of the fields available to edit. **You can view the full form [here](https://participedia.net/case/new?full=1).** For more information about this form, please [review our guidelines](https://docs.google.com/document/d/19Pc9qL3H1SxSByuQY1HxLOgbbMQpnnxlicdMGuC78Wg/edit?usp=sharing).

**Comment by jesicarson** [comment]
@ascott when you have a moment, let me know if you think this idea is workable. It could be its own separate prompt, but I think it makes sense to lump it in with this existing one. Open to your thoughts. Thanks!

Guidelines Links...
Cases: https://docs.google.com/document/d/19Pc9qL3H1SxSByuQY1HxLOgbbMQpnnxlicdMGuC78Wg/edit?usp=sharing
Methods: https://docs.google.com/document/d/19Pc9qL3H1SxSByuQY1HxLOgbbMQpnnxlicdMGuC78Wg/edit?usp=sharing
Organizations: https://docs.google.com/document/d/19Pc9qL3H1SxSByuQY1HxLOgbbMQpnnxlicdMGuC78Wg/edit?usp=sharing

**Comment by jesicarson** [comment]
Just realized those links all go to the same document, which is not yet ready for distribution (#1126) 

Here are the actual links (need to decide whether to link to full or abridged cases guidelines in the prompt and on FAQ - @plscully pls advise thanks):

cases full: https://docs.google.com/document/d/1FuBBhVoKi-KzXQXDSU8DzoRFArLNsur40Q1NvnfmPrA/edit?usp=sharing

cases abridged: https://docs.google.com/document/d/1lh4-hVAnl9o-yFW91eJlAN78Mujimx4tUPqOewyp5ZI/edit?usp=sharing

methods full: https://docs.google.com/document/d/1Lgw_R5h5dsk-O4WYDBD7feLvRtwtq5wnXysJ6qp8veE/edit?usp=sharing

orgs full: https://docs.google.com/document/d/12QmZZBupsm2F73RnKNOqTLnaSl3CdzlWEfvv-XW4U34/edit?usp=sharing

**Comment by jesicarson** [comment]
@plscully can we link to lucy's new guidelines rather than separate docs for each entry type in the prompt?

**Comment by plscully** [comment]
It seems by the time someone gets to the data entry form that we would want to give them the most detailed guidelines we have for each entry type.  Is there a reason we shouldn't do that?

**Comment by jesicarson** [comment]
sure we can do that. i wasn't sure if you were going to stop using the full documents and keep to one, shorter guidelines doc in the future. But if you want to keep the full ones we can link them here.

**Comment by plscully** [comment]
@jesicarson Hmm, now that I look at this again, I am really confused. There are so many versions of the "short" guidelines that I've lost track.  In [this document](https://docs.google.com/document/d/1zYNsWr4SSvIobGRviJ9EHDlVRawbu9KV8HqrjWm3blg/edit) that I created early this summer to advise Antonin, Veronica, and Jaskiran, the first item on this is what Scott called the "key considerations" document, which now that I look at it seems to be yet another version of the short guidelines.  Please check with Jaskiran & Lucy to see how they see the difference or similarities b/w the "key considerations" and the "guide to participedia" and the document that Lucy is working on. ... It looks as though "key considerations" only focuses on the narrative, but if that's true, then maybe that should simply be incorporated into the piece that Lucy is working on.

**Comment by jesicarson** [comment]
@plscully yes, the many documents does feel a bit overwhelming, which is why I was thinking maybe consolidating into one (much shorter) document might be best. But I will defer to the editing team to communicate their needs, and D&T will link up the site accordingly. 
I had a thought that we should have an actual guidelines page on the site so that we could localize it into our supported languages also... but that leaves much less flexibility in terms of ongoing updating by the editing team.

**Comment by ascott** [comment]
@plscully @jesicarson i'm going to add this to the site today. did we decide on what links we wanted to use?

**Comment by ascott** [comment]
for reference we currently link to this document from the info text in the narrative:
https://docs.google.com/document/d/1lzhV6aoslzqaj9XhOtVUOHbSJYOPK0tiXg0ALzIkN-w/edit

i think we should link to the same guidelines document from both of these links, at the top of the screen and in the body info text..

<img width="641" alt="Screen Shot 2020-09-04 at 12 34 02 PM" src="https://user-images.githubusercontent.com/130878/92278977-28d3aa00-eeab-11ea-9d1d-f274587784ce.png">

**Comment by plscully** [comment]
@ascott @jesicarson I’ve thought about this a bit more since yesterday. I think this piece of work began a couple of weeks ago when Jesi & I suggested we update the notice displayed in the data entry form right below “Quick Submit” so that it includes a 3rd sentence that reads: “For more information about this form, please review our guidelines”. Lucy, Jesi and I subsequently updated this set of guidelines, which has been re-titled “A Quick User Guide to Participedia.”  https://docs.google.com/document/d/1AAaZNQX9QvrPLP1DrOHRf5PlRSVhjKoEfQWsil5dygo/edit  
We signed off on this new document yesterday and my understanding was that Jesi was going to paste the new text over the text in the link that Alanna shared a few minutes ago, thereby doing away with the need for Alanna to change at least some of the links. This still makes sense to me, AND I have a few other recommendations for how we should complete the various changes we need to make to the different types of guidelines:
1. Yesterday Jesi linked to the new User Guide in: What is a Case? What is a Method? and What is an Organization?” items in the help & contact menu. However it looks like she used the new link instead of pasting the new text into the old g-doc
2. I think it still makes sense to also link to the new User Guide in the notice that is at the start of the Quick Submit.
3. Then if a user selects the full form, they would again see only the third sentence of the notice used at the start of the form: “For more information about this form, please review our guidelines” immediately above ‘OVERVIEW.” 
 4. We can change the links in the notices that are immediately above the Narrative boxes for each entry type so that the link goes to the long-form version of that entry type’s guidelines, which are:
Cases: https://goo.gl/FZJgMm 
Methods: https://goo.gl/p6HYNk 
Organizations: https://goo.gl/t2bDw4
Lucy and I will be updating these last three guidelines documents in coming weeks, but they work fine for now.

**Comment by jesicarson** [comment]
@ascott FYI the "key considerations" doc (https://docs.google.com/document/d/1lzhV6aoslzqaj9XhOtVUOHbSJYOPK0tiXg0ALzIkN-w/edit) is the one I mentioned that will no longer be used.  

@plscully - to confirm: We'll link to the "long form" guidelines _only_ in the narrative explanatory text for each entry type, and in _all_ other places link to the new "quick user guide." 

If either of you want to hop on a call or chat on slack to clarify the plan here, let me know.

**Comment by plscully** [comment]
@jesicarson Yes, We'll link to the "long form" guidelines only in the narrative explanatory text for each entry type, and in all other places link to the new "quick user guide."

**Comment by ascott** [comment]
@jesicarson re: your idea about adding the guidelines link at the stop with the quick submit alert text.

> This is the quick/short form and only contains a subset of the fields available to edit. You can view the full form here. For more information about this form, please review our guidelines.

in this case we would only be showing this alert when on the quick submit form, so i'm thinking this text about the guidelines should be separate from the quick submit alert. what do you think?

**Comment by jesicarson** [comment]
@ascott yes, I agree. i think we discussed on our last call that you'd add the link to the guidelines to the top of the form - I was picturing it as a short explanatory text line below the title of the form (both quick and long versions). Rather than including it as yet another alert, that is.

**Comment by ascott** [comment]
@jesicarson ok great. here are screenshots of what i have currently. what do you think?

<img width="1440" alt="Screen Shot 2020-09-10 at 9 52 42 AM" src="https://user-images.githubusercontent.com/130878/92766863-76d52b80-f34b-11ea-9868-a2f5fd55e6ae.png">
<img width="1440" alt="Screen Shot 2020-09-10 at 9 52 32 AM" src="https://user-images.githubusercontent.com/130878/92766868-776dc200-f34b-11ea-856a-c9ca2702e568.png">

**Comment by jesicarson** [comment]
looks good, but i would keep the explanatory text anchored to the page title, with the alert below that
