### ISSUE TITLE
Usersnap Feedback - All the links to guidelines currently in the FAQ go to the same document, [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1126]
**Sender**: jesi.carson@gmail.com
**Comment**: All the links to guidelines currently in the FAQ go to the same document, which is DRAFT - not ready for distribution. We should update to the existing guidelines docs.
[Open #815 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/815)

<a href='https://usersnappublic.s3.amazonaws.com/2020-08-26/23-23/46d520f8-195e-4b70-8e99-7ff2211eb044.png'>![Usersnap Feedback - All the links to guidelines currently in the FAQ go to the same document, (...)](https://usersnappublic.s3.amazonaws.com/2020-08-26/23-23/127579ed-b783-4376-b8eb-6bece3a50501.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-08-26/23-23/46d520f8-195e-4b70-8e99-7ff2211eb044.png'>Download original image</a>

**Browser**: Chrome 84 (Macintosh)
**Referer**: [https://participedia.net/#](https://participedia.net/#)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
cases full: https://docs.google.com/document/d/1FuBBhVoKi-KzXQXDSU8DzoRFArLNsur40Q1NvnfmPrA/edit?usp=sharing

cases abridged: https://docs.google.com/document/d/1lh4-hVAnl9o-yFW91eJlAN78Mujimx4tUPqOewyp5ZI/edit?usp=sharing

methods full: https://docs.google.com/document/d/1Lgw_R5h5dsk-O4WYDBD7feLvRtwtq5wnXysJ6qp8veE/edit?usp=sharing

orgs full: https://docs.google.com/document/d/12QmZZBupsm2F73RnKNOqTLnaSl3CdzlWEfvv-XW4U34/edit?usp=sharing

**Comment by plscully** [comment]
@jesicarson The link goes to a version that although it is marked "draft" is pretty strong. Let's leave the link in while Lucy works on the update. I changed the file name so that it doesn't say "draft". ... This is an important document, though, and I hadn't realized that it was such a key link, so we need to make it a high priority. Can you please check in with Lucy (I think her conference is almost over) and then maybe we could set aside a few hours someday soon for the three of us to hack our way through it at the same time.

**Comment by jesicarson** [comment]
Sounds good thanks @plscully we will leave these in the FAQ section. Does this mean we should be linking to this new guidelines document in the entry forms as well? Re, this issue: #1125
