### ISSUE TITLE
Usersnap Feedback - The original entry is in English, so the open text should either be empty [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1129]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: The original entry is in English, so the open text should either be empty or at least some of it should be in French
[Open #818 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/818)

<a href='https://usersnappublic.s3.amazonaws.com/2020-08-28/15-47/203c40af-5fe7-4ff6-9f6b-484814b6097b.png'>![Usersnap Feedback - The original entry is in English, so the open text should either be empty (...)](https://usersnappublic.s3.amazonaws.com/2020-08-28/15-47/1545b21b-d661-4268-bafe-967350444727.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-08-28/15-47/203c40af-5fe7-4ff6-9f6b-484814b6097b.png'>Download original image</a>

**Browser**: Firefox 79 (Windows 10)
**Referer**: [https://participedia.net/case/6573](https://participedia.net/case/6573)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 958

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Test entry (hidden) https://participedia.net/case/6890 - I entered text in english while using the french interface. Funny enough, it translates correctly to the other languages, except french, which remains English. Therefore, the case referenced in this issue wasn't entered while using the site in another language, as english is displayed in all language versions. So not sure what the problem is here.. need to double check the launch date for user entered text localization to see if this case was published prior to or since the launch. According to the wiki contributor history dropdown, the first author was June 1, 2020 | Antonin L Webster (he's on the participedia team also, so we can reach out to him if needed).

**Comment by paninee** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/29439995/113195859-a54b2300-9217-11eb-9eaf-1b427c33a2a9.png)
