### ISSUE TITLE
Usersnap Feedback - all the options are already shown (the same applies to the filter for face[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1165]
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: all the options are already shown (the same applies to the filter for face-to-face interaction, online, or both)
[Open #854 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/854)

<a href='https://usersnappublic.s3.amazonaws.com/2020-10-04/04-14/cafd9755-fe98-4bde-bbaf-e3ac45c32fe1.png'>![Usersnap Feedback - all the options are already shown (the same applies to the filter for face(...)](https://usersnappublic.s3.amazonaws.com/2020-10-04/04-14/6c9907bf-eb9e-4dbd-bfa1-72aa3b41f07c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-10-04/04-14/cafd9755-fe98-4bde-bbaf-e3ac45c32fe1.png'>Download original image</a>

**Browser**: Safari 12 (macOS Mojave)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/search?selectedCategory=case&scope_of_influence=multinational](https://participedia-homepage-2020.herokuapp.com/search?selectedCategory=case&scope_of_influence=multinational)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 837

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
i cant reproduce this. i'll ask jaskiran to clarify.

**Comment by jesicarson** [comment]
from jaskiran: hi Jesi, I was actually referring to the “open to all or limited to some” search filter. I’m not sure why the image here appears to be pointing at a different section than what I was seeing but at any rate, it was just a minor note that the “show all” button doesn’t really seem to serve a purpose since all of the options are already shown (and that the same applies to the face-to-face interaction, online, or both filter). Hope that makes sense, sorry for the confusion!
