### ISSUE TITLE
Usersnap Feedback - I’ve not been able to login today on my iPad, though my phone & Windows de[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#120]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: I’ve not been able to login today on my iPad, though my phone & Windows desktop work fine. After entering address & pswd, the login button is no responsive 
[Open #134 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/134)

<a href='https://usersnappublic.s3.amazonaws.com/2017-10-26/21-25/626334da-d404-4891-9ad7-5e5dc1805072.png'>![Usersnap Feedback - I’ve not been able to login today on my iPad, though my phone & Windows de(...)](https://usersnappublic.s3.amazonaws.com/2017-10-26/21-25/eeb50fc8-876c-490a-8b01-3379e839588f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-10-26/21-25/626334da-d404-4891-9ad7-5e5dc1805072.png'>Download original image</a>

**Browser**: ChromeiOS 61 (iOS)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 768 x 1024 **Browser size**: 768 x 1024

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
I was able to replicate this once (on desktop, in Firefox) by clicking Login, clicking LinkedIn icon, then cancelling (since I don't use LinkedIn). Got infinite spinner and no way to get out besides reloading page. Now when I try the same thing I get to an empty front page, no data loads. I can replicate that by starting login via LinkedIn, Twitter, or Facebook, but cancelling instead of finishing login. Google does not provide an option to cancel once you've begun login, so I had to reload the page instead, which loaded content normally.
