### ISSUE TITLE
Usersnap Feedback - Spam user account - looks like a bunch of accounts from "effobe.com" in Au[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1322]
**Sender**: jesi.carson@gmail.com
**Comment**: Spam user account - looks like a bunch of accounts from "effobe.com" in Auth0, along with a number of additional suspicious looking accounts added in the last 10-20 hours. @ascott
[Open #1010 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1010)

<a href='https://usersnappublic.s3.amazonaws.com/2020-12-30/01-17/ed69ff48-2175-48ec-88f6-447e203ae199.png'>![Usersnap Feedback - Spam user account - looks like a bunch of accounts from "effobe.com" in Au(...)](https://usersnappublic.s3.amazonaws.com/2020-12-30/01-17/203ef27b-8669-4cb5-94c1-42d467c46cdb.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-12-30/01-17/ed69ff48-2175-48ec-88f6-447e203ae199.png'>Download original image</a>

**Browser**: Chrome 87 (Macintosh)
**Referer**: [https://participedia.net/user/419700](https://participedia.net/user/419700)
**Screen size**: 1920 x 1080 **Browser size**: 1341 x 925

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
I blocked all the effobe.com accounts from the last few days, but I would like to check the DB and confirm that the nedoz.com accounts are also spam - @ascott how can I do this? Looking back in Auth0 i can tell there are a bunch of spam-looking accounts, but I don't know how to verify, since we don't have a users listing on the site. Thanks!

**Comment by jesicarson** [comment]
Also - even if I block a user, their spam profile page (full of junk/links) is still visible on the site, and therefore google can index these pages. We need system for admins to be able to both find and hide spam user account pages..

**Comment by plscully** [comment]
@jesicarson Thank you for the update. I discovered the latest spam user from the following email sent to me last night by Scott: "I just wanted to let you know right now that I got a Google alert for Participedia and it appears to be spam. Here's the link so you can take it down: https://participedia.net/user/419700 " 
BTW, I check the case, method, and org entries for spam first thing every day.

**Comment by jesicarson** [comment]
Great to hear that Scott has eyes on the site! 
I also got that google alert, but haven't gotten any others, which seems strange since I see so many accounts with the same @ effoby.com domain. I blocked them all to be on the safe side until Alanna can review. Unfortunately, I can't delete the spam user profile from the site without a dev at this time.
