### ISSUE TITLE
Usersnap Feedback - Spam - Please block this user and delete any content they may have posted

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1323]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Spam - Please block this user and delete any content they may have posted
[Open #1011 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1011)

<a href='https://usersnappublic.s3.amazonaws.com/2020-12-30/14-55/c467d2db-6f40-4642-a75d-b684c6d7e492.png'>![Usersnap Feedback - Spam - Please block this user and delete any content they may have posted](https://usersnappublic.s3.amazonaws.com/2020-12-30/14-55/22d62692-63a4-4855-840e-5e1b59609d0b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-12-30/14-55/c467d2db-6f40-4642-a75d-b684c6d7e492.png'>Download original image</a>

**Browser**: Firefox 84 (Windows 10)
**Referer**: [https://participedia.net/user/419700](https://participedia.net/user/419700)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@plscully I blocked this user yesterday, and it looks like they didn't post anything yet. The issue seems to be spammers creating user accounts, so they end up with profile pages on our site full of junk/links, and in addition the pages can't be deleted by an admin (only a dev). see #1322. We will likely need a system for deleting spam user profiles similar to the way we can "hide" entries. Both alanna and pan are on holidays, so for now I'll go in and block all the suspicious accounts and we can address the issue in January. The good news is that it looks like a lot of these spammers aren't publishing entries (yet), and since we don't list users in search results, their spam user profile pages are not "findable" via our site search. however, my main concern is that google will index the user profile pages and lead people to spam pages on our site...
