### ISSUE TITLE
Consider adding "download results csv" button to All tab on collections and search page

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1335]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Now that we have some fairly large collections--eg "ScienceWise" and the OECD--It would be useful to be able to filter for a collection so that users can download a CSV for it.
[Open #1023 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1023)

<a href='https://usersnappublic.s3.amazonaws.com/2021-01-25/17-26/7c133915-99a5-4972-9651-7750726f4c83.png'>![Usersnap Feedback - Now that we have some fairly large collections--eg "ScienceWise" and the O(...)](https://usersnappublic.s3.amazonaws.com/2021-01-25/17-26/207511c7-e100-4813-a4b9-a351807dd6f7.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-01-25/17-26/7c133915-99a5-4972-9651-7750726f4c83.png'>Download original image</a>

**Browser**: Firefox 84 (Windows 10)
**Referer**: [https://participedia.net/search?selectedCategory=case&openFilters=1](https://participedia.net/search?selectedCategory=case&openFilters=1)
**Screen size**: 1760 x 1100 **Browser size**: 1760 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
Hi @plscully. Good to know that filters for collections might be useful, I'll add this to our potential projects list. For now researchers can work with the existing, full csv's for collections and do manual further filtering via R, etc. Should we note this in the guidelines perhaps?

**Comment by plscully** [comment]
@jesicarson I'm looping @vhurtadol into this discussion because she's in a better position to say how easy it will be for the average user to do isolate cases that are in a collection by using R or even a basic sort of a csv file to do a manual filtering of the full data set. One thing to keep in mind is a decision I believe we made in our last meeting with Matt that whenever possible we should design the data retrieval process so that it is easily understood by people who don't have much experience with this sort of thing. We'd love to hear your thoughts about this Vero!

**Comment by jesicarson** [comment]
@plscully we can already download cases, methods and organizations csv's for each collection. Is what you mean by isolating cases that are in each collection? I only meant that if further filtering is needed (of the already filtered collection) then R or excel may be used, for now. 

![Screen Shot 2021-01-25 at 3 17 37 PM](https://user-images.githubusercontent.com/13560530/105778136-8df26f80-5f20-11eb-903a-fb242d804207.png)

**Comment by plscully** [comment]
@jesicarson Oh, I see now! I wasn't seeing the csv download button because I hadn't selected for one of the three entry types.  I of all people should have noticed this.  I'm sorry to have caused confusion about this.

**Comment by jesicarson** [comment]
That's ok - its a good point, actually. for filters on the search page we show the "filters" button on the "all" tab even though it pushes people to filter cases (so that they see that filters exist!). We don't show the "download results CSV" button on the "all" tab... but maybe we should? Could give users the option to select Cases, Methods or Organizations, or a zip file with all 3 csv's perhaps? I'll run this by D&T and see how hard it would be.

**Comment by plscully** [comment]
@jesicarson My guess is that it's less important to give users the option of downloading csv's for all three types with one click than it is to provide redundant directions on what you can download from each page view

**Comment by vhurtadol** [comment]
> @jesicarson I'm looping @vhurtadol into this discussion because she's in a better position to say how easy it will be for the average user to do isolate cases that are in a collection by using R or even a basic sort of a csv file to do a manual filtering of the full data set. One thing to keep in mind is a decision I believe we made in our last meeting with Matt that whenever possible we should design the data retrieval process so that it is easily understood by people who don't have much experience with this sort of thing. We'd love to hear your thoughts about this Vero!

Hi all! I think the current system of downloading the cases/methods of a specific collection as a CSV file works great! I agree with @plscully that making it clear for users that they can get the CSV they are interested in through the different tabs is good. Personally, downloading zip files with information that I might not be interested in can be messy. 

Maybe (if you think there is space to put a note) we should indicate that for a complete list of the participatory processes, researchers can download the full CSV file.

**Comment by jesicarson** [comment]
Great feedback thanks folks!

**Comment by jesicarson** [comment]
covered by https://github.com/participedia/usersnaps/issues/1338 closing
