### ISSUE TITLE
Usersnap Feedback - Has the landing page changed in the last few days? This screenshot is from [...]

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1365]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Has the landing page changed in the last few days? This screenshot is from my laptop and the "browse all entries" option is not showing
[Open #1048 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1048)

<a href='https://usersnappublic.s3.amazonaws.com/2021-04-27/21-04/9b6c48d4-7611-49cb-8bcb-2ac1a35b52b9.png'>![Usersnap Feedback - Has the landing page changed in the last few days? This screenshot is from (...)](https://usersnappublic.s3.amazonaws.com/2021-04-27/21-04/384ff63b-123c-4f38-91a9-68e410bd25e9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-04-27/21-04/9b6c48d4-7611-49cb-8bcb-2ac1a35b52b9.png'>Download original image</a>

**Browser**: Firefox 88 (Windows 10)
**Referer**: [https://participedia.net/](https://participedia.net/)
**Screen size**: 1280 x 720 **Browser size**: 1280 x 579

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
Hi @plscully what size is your browser window? When you resize the window, we have "break points" set where less items will display so that they don't get all bunched up on smaller screens. If you stretch your window out a bit, you might notice the elements coming back. I'm looking at the site now and it's working correctly, but if you resize to your full width and height and you're still not seeing everything, let us know. 

<img width="1246" alt="Screen Shot 2021-04-27 at 12 14 44 PM" src="https://user-images.githubusercontent.com/13560530/116299171-34355780-a752-11eb-9967-40d67002a846.png">
 
<img width="845" alt="Screen Shot 2021-04-27 at 12 14 25 PM" src="https://user-images.githubusercontent.com/13560530/116299154-2f70a380-a752-11eb-91dc-2251ab5bbe86.png">

<img width="1261" alt="Screen Shot 2021-04-27 at 12 14 36 PM" src="https://user-images.githubusercontent.com/13560530/116299165-326b9400-a752-11eb-802e-20d92188d70b.png">

**Comment by jesicarson** [comment]
Pat - feel free to re-open this if you're still having problems with the display.
