### ISSUE TITLE
Usersnap Feedback - Two quick issues:  1. All the authors of cases are Lucy Parry! Original au[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#142]
**Sender**: g.smith@westminster.ac.uk
**Comment**: Two quick issues:

1. All the authors of cases are Lucy Parry! Original authors will not be happy...

2. All the case creation dates are March 2018. Can we transfer the original dates? 

Cheers

G.
[Open #156 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/156)

<a href='https://usersnappublic.s3.amazonaws.com/2018-03-19/16-32/b6b62b38-2bf0-46f9-850c-5162690fcf17.png'>![Usersnap Feedback - Two quick issues:  1. All the authors of cases are Lucy Parry! Original au(...)](https://usersnappublic.s3.amazonaws.com/2018-03-19/16-32/2310c8c5-0137-4bdf-8d57-78888169bc08.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-03-19/16-32/b6b62b38-2bf0-46f9-850c-5162690fcf17.png'>Download original image</a>

**Browser**: Firefox 58 (OS X El Capitan)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 729

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
The "all names are Lucy Parry" issue will be fixed in the API: https://github.com/participedia/api/issues/271

The featured articles have the date they were last modified, which is the date they were featured. We're now discussion whether it is better to show and sort by last modified or original creation date, and whether featuring a article should update its last modified date, but that isn't broken, per se.
