### ISSUE TITLE
Usersnap Feedback - This font & spacing look different from other entries. I think this is Tim[...]

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1538]
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: This font & spacing look different from other entries. I think this is Times 12 instead of our usual  Calibri  11. Aren't users forced into using our default font? Odd formatting seems to happen with a lot of the entries from Paolo's students. I wonder if that is because he has them cut & past from another document.
[Open #1219 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1219)

<a href='https://usersnappublic.s3.amazonaws.com/2021-12-06/23-45/987d0e75-2027-4508-a41c-a3b00d7436b6.png'>![Usersnap Feedback - This font & spacing look different from other entries. I think this is Tim(...)](https://usersnappublic.s3.amazonaws.com/2021-12-06/23-45/7837cc2c-92ea-4bf7-8c36-5295f7ceab76.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-12-06/23-45/987d0e75-2027-4508-a41c-a3b00d7436b6.png'>Download original image</a>

**Browser**: Firefox 94 (Windows 10)
**Referer**: [https://participedia.net/case/7393](https://participedia.net/case/7393)
**Screen size**: 1600 x 1000 **Browser size**: 1600 x 896

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
Thanks Pat!

I tried but I can't fix this by clicking the clear formatting button in the form. Will add to backlog for @paninee to review.

**Comment by paninee** [comment]
@plscully @jesicarson  this isn't Times font. They are `"Fakt", "Avenir", sans-serif` same as the rest of the page. The spacing happens because the user hit "enter" on those every single line of content. It creates a new `<p>` element in the WYSIWYG editor.
![image](https://user-images.githubusercontent.com/29439995/146903553-34c75154-6694-4941-b269-2594cbd725d9.png)

I tried deleting a new line character (enter) don't eh first line of text and that fixes the problem. This is a data issue, not code.
![image](https://user-images.githubusercontent.com/29439995/146903748-317f4844-eabd-4249-9655-0ad5bb8eede1.png)

**Comment by plscully** [comment]
@paninee Thank you for sorting this out.  I fixed the text. This also gave me some good experience using the new captcha feature.

**Comment by jesicarson** [comment]
Ok great. Maybe they copied the text from a PDF or something, which included the line breaks. Since this is fixed by @plscully I'll close this issue.
