### ISSUE TITLE
Usersnap Feedback - Searching for a method is nearly impossible. I've tried this with a couple [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#157]
**Sender**: scottowenfletcher@gmail.com
**Comment**: From Lucy: Searching for a method is nearly impossible. I've tried this with a couple methods and despite entering the exact entry name (in this case 'town hall meeting'), the first hit (even the first ten hits) is never that entry. 
[Open #170 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/170)

<a href='https://usersnappublic.s3.amazonaws.com/2018-04-16/18-33/05992461-3a7b-40b6-bf91-983c2375ea3a.png'>![Usersnap Feedback - Searching for a method is nearly impossible. I've tried this with a couple (...)](https://usersnappublic.s3.amazonaws.com/2018-04-16/18-33/d22befda-2cc0-4a4b-bc7b-d60bcdb2e6ea.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-04-16/18-33/05992461-3a7b-40b6-bf91-983c2375ea3a.png'>Download original image</a>

**Browser**: Chrome 65 (Windows 10)
**Referer**: [https://participedia.xyz/methods?query=town%20hall%20meeting](https://participedia.xyz/methods?query=town%20hall%20meeting)
**Screen size**: 1280 x 720 **Browser size**: 1600 x 737

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
This was weird, because of something unexpected (by me) in the SQL layer. We have one query which gets ALL search results and returns them ranked in order of how well they match the search terms. What was odd was that when I looked at the ranks, the result for this query should have been at the top, so something was reversing the order. That query feeds into another query which mainly just does pagination, returning each group of 20 results. I expected that they would have their order maintained, but that was the assumption that was wrong. So if a result should have been at the top of the first page, it would still be on the first page, but last. Added ordering to the second query and now this query returns in the first row when all items are searched.

Note: searching by article type (Case/Method/Organization) is the one facet we do support, so if you click the tab for Methods, all your search results will be Methods.
