### ISSUE TITLE
[USERSNAP] Trying to change authorship (edit submission details) from user: Bagonbile to user: 3569822 and i'm getting an error

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1925]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/case/12320/edit
**Fields**:
- Add a comment: Trying to change authorship (edit submission details) from user: Bagonbile to user: 3569822 and i&#39;m getting an error

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/e4c02278-dc43-49d2-9c11-0e9bc7e4d63a-annotated_d51267fa-5926-4bea-b312-12606046743e.png?etag=4204aff964ad72d53ebd49995e744006)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/e4c02278-dc43-49d2-9c11-0e9bc7e4d63a-annotated_d51267fa-5926-4bea-b312-12606046743e.png?etag=4204aff964ad72d53ebd49995e744006)*

**Browser**: Chrome 110 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1710x893
**[Open #1608 in Usersnap](https://app.usersnap.com/l/feedback/6db071fe-b45e-414d-9ada-91ed21d108d7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
i'm pretty sure there were no edits by this user in the wiki contributor history before I attempted to change authorship... but now user 3569822 is showing up on feb 27th (rather than as the original author, as I had intended). I tried refreshing after clicking OK on the error message (which worked to reassign authorship on the previous entry by nancy), but didn't have success this time. 
<img width="727" alt="Screenshot 2023-02-28 at 11 19 41 AM" src="https://user-images.githubusercontent.com/13560530/221957106-035d26fb-056c-4a6b-a068-5ef167409d16.png">

**Comment by jesicarson** [comment]
see also nancy's entry, where clicking refresh DID work to complete the publish: #1924
