### ISSUE TITLE
[USERSNAP] fix authorship - manually reassign to user (form not working)

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1961]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/case/12320
**Fields**:
- Add a comment: Updating original authorship not working. I thought this was fixed? Maybe its just this entry that&#39;s a problem? I entered the name of this user (which is a number) https://participedia.net/user/423267 , but it still shows Adam Cronkright as the original author.

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/e9ce81b7-05a8-4cce-b47b-4b6eef14064b-annotated_adc6a7ac-c5b5-4daa-b233-3b2e79b1ee86.png?etag=0552ebc81383cede1bd2894695fff8f2)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/e9ce81b7-05a8-4cce-b47b-4b6eef14064b-annotated_adc6a7ac-c5b5-4daa-b233-3b2e79b1ee86.png?etag=0552ebc81383cede1bd2894695fff8f2)*

**Browser**: Chrome 114 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1633x816
**[Open #1644 in Usersnap](https://app.usersnap.com/l/feedback/989faef0-eae7-4e3d-973b-80cda76ca6ee?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee could you manually reassign the original author for this entry to this user: https://participedia.net/user/423267 please? thanks! 

The users name is Beverley Adonis, but they never updated their profile from their number-based email address. 

I was able to reassign authorship on another entry without any issues, so it appears it is only this case/user that is affected - or perhaps all users with numbers instead of a name? not sure.

**Comment by jesicarson** [comment]
@paninee I got it to work by using their full email address, not just the clipped "name" in the edit form. so nevermind, this is fine. closing
