### ISSUE TITLE
Usersnap Feedback - Case data BUGS  Can't delete components / Duplicate components

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#199]
**Sender**: jesi.carson@gmail.com
**Comment**: Components BUGS

BUG 1 Can't delete components (in edit view, they disappear when I click the X, but they still show in the sidebar when published)

BUG 2 Duplicate components listed (same as duplicate methods bug)
[Open #212 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/212)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-19/18-36/7e13b27a-a6a3-401c-a2ab-318a96481c5c.png'>![Usersnap Feedback - Components BUGS  BUG 1 Can't delete components (in edit view, they disappe(...)](https://usersnappublic.s3.amazonaws.com/2018-06-19/18-36/88eecf29-af04-4d7a-833e-0b075bab822b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-19/18-36/7e13b27a-a6a3-401c-a2ab-318a96481c5c.png'>Download original image</a>

**Browser**: Chrome 67 (Macintosh)
**Referer**: [https://participedia.xyz/case/4512](https://participedia.xyz/case/4512)
**Screen size**: 1280 x 800 **Browser size**: 1258 x 680

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@dethe the part about not being able to save changes (bug 1) may be related to the methods form saving issues you've been working on? Looks like this problem is popping up randomly in cases as well.

**Comment by dethe** [comment]
Not being able to remove components is a different problem, and turns out to be kind of tricky because of the way we allow you to add component via either "this is a component of that" or "this has these components". As a work-around for now I will have to turn off "this has these components" in the editing view (they will still show in the details view) until I have time to figure out how to handle it better.
The workaround for that limit is to go to each component and set "this is a component of _____". Which I know is a hassle, but it will work for now while I figure out the rest.

Other than that limit a fix is on the way.

**Comment by jesicarson** [comment]
Ok thanks @dethe. Let us know when that is turned off and we can remove components - I was doing some testing yesterday and should remove them before I forget.
