### ISSUE TITLE
[USERSNAP] Entry cards not displaying images (this entry does have an image, I checked)

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1995]
**Sender**: jesi.carson@gmail.com
**Taken at**: https://participedia.net/search?selectedCategory=case&layout=maps
**Fields**:
- Add a comment: Entry cards not displaying images (this entry does have an image, I checked)

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/b033d2a0-4eb6-40f5-aeeb-5c58cff6c934-annotated_d21b318a-231d-4ef5-b9f3-7776d1aaf56a.png?etag=10afa83b302570af2e4eb2d85f396fc2)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/b033d2a0-4eb6-40f5-aeeb-5c58cff6c934-annotated_d21b318a-231d-4ef5-b9f3-7776d1aaf56a.png?etag=10afa83b302570af2e4eb2d85f396fc2)*

**Browser**: Chrome 118 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1801x881
**[Open #1678 in Usersnap](https://app.usersnap.com/l/feedback/bf5fb7d2-893d-47a7-b92d-1edb9461caa5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
@paninee I still see a handful of entries without placeholder images on the site. Should we re-open this issue - or is there another one dealing with results images (rather than map)?

<img width="1440" alt="Screenshot 2024-01-02 at 12 20 02 PM" src="https://github.com/participedia/usersnaps/assets/13560530/489806a0-bb4d-4cef-85da-c9eb3eb55fc0">
