### ISSUE TITLE
Usersnap Feedback - Cannot open more than one external link in different tabs - if I open one [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#216]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Cannot open more than one external link in different tabs - if I open one link in a tab (CTRL+left click) and then another, the second just loads in the same tab as the first. This is highly problematic as I'm often having to open an entire list of links to check that they are working
[Open #229 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/229)

<a href='https://usersnappublic.s3.amazonaws.com/2018-07-03/00-22/5f87568b-2936-4508-84e1-f1a04bdae750.png'>![Usersnap Feedback - Cannot open more than one external link in different tabs - if I open one (...)](https://usersnappublic.s3.amazonaws.com/2018-07-03/00-22/7f75e928-98c2-46d6-b1fe-59535edeaaa3.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-07-03/00-22/5f87568b-2936-4508-84e1-f1a04bdae750.png'>Download original image</a>

**Browser**: Firefox 61 (Windows 10)
**Referer**: [https://participedia.xyz/case/1083/edit](https://participedia.xyz/case/1083/edit)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 876

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@scottofletcher I remember a discussion about opening hyperlinks from forms - can you help me find where that is and reference this there? Thanks!

**Comment by scottofletcher** [comment]
Was it this one participedia/frontend#798 ?

**Comment by jesicarson** [comment]
@scottofletcher Hmm no it wasn't that one. @dethe was involved in the conversation when we talked about your workflow for checking if links are not broken - via the form (rather than via the reader) - and dethe mentioned (I think) that it's not common practice to open hyperlinks from text edit form fields, and you mentioned (I think) that you would like to be able to do that because you want to check a lot of links at once sometimes (like this issue mentions). But I don't remember if this conversation was in an issue or on slack or what we decided to do (sorry, baby brain).

**Comment by scottofletcher** [comment]
Aha! I think it's this one participedia/frontend#869

**Comment by jesicarson** [comment]
Yes!
I was thinking of this, from Dethe: "Clicking on a link in edit mode should never open up the link, it should always bring up a select menu because you are editing, not browsing."

**Comment by ascott** [comment]
fixed with this PR https://github.com/participedia/api/pull/354
