### ISSUE TITLE
Usersnap Feedback - I keep being logged out when I'm editing!

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#247]
**Sender**: scottowenfletcher@gmail.com
**Comment**: I keep being logged out when I'm editing!
[Open #260 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/260)

<a href='https://usersnappublic.s3.amazonaws.com/2018-08-21/19-50/4067c3df-832f-4cbe-9791-59125d77b338.png'>![Usersnap Feedback - I keep being logged out when I'm editing!](https://usersnappublic.s3.amazonaws.com/2018-08-21/19-50/e5d267c9-32a3-455b-b368-6097187153cd.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-08-21/19-50/4067c3df-832f-4cbe-9791-59125d77b338.png'>Download original image</a>

**Browser**: Chrome 68 (Windows 10)
**Referer**: [https://participedia.xyz/case/5090/edit](https://participedia.xyz/case/5090/edit)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 803

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@scottofletcher, @dethe is looking into this.

**Comment by dethe** [comment]
Several problems: 

1. Our app caches some of the data that it should be clearing when a login expires (that's why it still shows your name and profile picture)
2. We should increase your login period every time you use the site (not sure if that was ever working, but it should)
3. Your login time can expire while you're on the site with no notification to you (this was always a problem, will fix after big move to backend)

4. The timeout may be too short (should be at least 24 hours from login). All of these are problems, which I will address along with moving away from Auth0, but if there is a workaround for now, that would be good.

**Comment by dethe** [comment]
After further investigation, there are two timeouts, one for the login token (which is set to 10 hours) and one for the login id (which defaults to 2 hours). These are unrelated, and I cannot change the id timeout (which is what we use), only @davidascher can. So it is silently timing out after 2 hours, which sucks.

@davidascher, if you get a chance can you bump up the timeout (in the API section of Auth0 settings, which it won't show me) to 10 hours to match the JWT timeout?

For now I am adding a timer which will switch your avatar back to the login button when the login time expires and add a hover to let you know how long until automatic logout. 

This is a temporary workaround until I can implement at better fix to extend login time when you're actively working.

**Comment by scottofletcher** [comment]
Thanks @dethe!
