### ISSUE TITLE
Usersnap Feedback - Is it possible to automatically break hyperlinks to 'hidden' entries? Othe[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#291]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Is it possible to automatically break hyperlinks to 'hidden' entries? Otherwise I have to go through and manually remove them.
[Open #303 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/303)

<a href='https://usersnappublic.s3.amazonaws.com/2019-02-16/17-41/e590a04e-d2aa-4ec1-b51d-b84a83e8c342.png'>![Usersnap Feedback - Is it possible to automatically break hyperlinks to 'hidden' entries? Othe(...)](https://usersnappublic.s3.amazonaws.com/2019-02-16/17-41/c9e24bc9-f340-4661-b539-ebc9c8fef6f3.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-02-16/17-41/e590a04e-d2aa-4ec1-b51d-b84a83e8c342.png'>Download original image</a>

**Browser**: Chrome 72 (Windows 10)
**Referer**: [https://participedia.xyz/method/159](https://participedia.xyz/method/159)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 867

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@scottofletcher Are there very many hyperlinks to hidden entries currently/ how often does this occur?

**Comment by scottofletcher** [comment]
@jesicarson I have absolutely no idea... I know Lucy linked to a lot of entries when she was cleaning up the method narratives and then we decided to 'hide' certain ones like 'deliberation' which we felt were too broad to be a method entry (and which we will include in the Glossary instead). Is there any way of seeing which entries link to what URLs?

**Comment by jesicarson** [comment]
I don't know any details about how to automate or what's possible, Dethe will have to weigh in on that.

I guess I'm asking, how often do you (or how often would the average site visitor) bump into this? Maybe deliberation was a big one, but going forward you might not be hiding as many things since the cleanup has already been done, is that right? I suppose if its easy to automate it might be worth it, but if its a big thing to build, it might not be worth worrying about too much. People can always hit the back button on the small chance they run into a hidden entry.

**Comment by dethe** [comment]
Automatically breaking links inserted into the narrative would be … tricky. We could redirect non-admin users if they hit a hidden page, or show them a message like "this content has been removed" though.

**Comment by scottofletcher** [comment]
That's actually the best course of action - ideally, only admins would be able to see/access 'hidden' content

**Comment by scottofletcher** [comment]
Should I create an issue for it?

**Comment by jesicarson** [comment]
"This content has been removed" message seems like a simple enough solution.

**Comment by scottofletcher** [comment]
should we include a contact email in case the person wants to know why it was removed?

**Comment by jesicarson** [comment]
Could do. I will mock this up. And, yes lets post a new issue (in api) to reflect this course of action, which is two fold in the instance that anyone visits a url that has since been hidden:
1. only admins are able to see/access 'hidden' content, with the toggle set to "hide," (so they could un-hide it, if they wanted to)
2. non admins will be served a "This content has been removed" message (possibly with a contact option TBC, jesi to provide mockup)
