### ISSUE TITLE
Usersnap Feedback - Entry not loading

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#331]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Entry not loading
[Open #305 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/305)

<a href='https://usersnappublic.s3.amazonaws.com/2019-03-12/23-37/29f92ac3-9615-4bac-ac00-b7fe8532d379.png'>![Usersnap Feedback - Entry not loading](https://usersnappublic.s3.amazonaws.com/2019-03-12/23-37/5bdef539-6964-4d01-87f1-67757c44c4e1.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-03-12/23-37/29f92ac3-9615-4bac-ac00-b7fe8532d379.png'>Download original image</a>

**Browser**: Chrome 72 (Windows 10)
**Referer**: [https://participedia.xyz/case/5596](https://participedia.xyz/case/5596)
**Screen size**: 1280 x 720 **Browser size**: 1707 x 771

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment]
@scottofletcher pretty sure i came across this same bug yesterday and have a fix for it. will test and push a fix later tonight.

**Comment by scottofletcher** [comment]
@ascott thanks! this is just one of many. I can't seem to identify a pattern, though. some tend to load until you edit them, but that's not always the case.

**Comment by ascott** [comment]
@scottofletcher i think the issue is that there are links that have been added that have no value: 
<img width="674" alt="Screenshot 2019-03-12 16 59 39" src="https://user-images.githubusercontent.com/130878/54244100-50c99380-44e8-11e9-9d32-809d555a9a81.png">

we should be removing those empty entries on the backend, but in the mean time i submitted a fix for the frontend if that happens. if we edit that case and remove the empty links on this case, then the page should load properly.

**Comment by scottofletcher** [comment]
ohhh, interesting! nice catch!

**Comment by ascott** [comment]
my fix didn't fix it for this case, since the first link wasn't empty, but the 2 and 3rd were, but i deleted the empty links and the reader view works now.  i will submit a  more robust fix for this issue.
