### ISSUE TITLE
Usersnap Feedback - none of the components I added appear in the sidebar (there are about 20)

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#343]
**Sender**: scottowenfletcher@gmail.com
**Comment**: none of the components I added appear in the sidebar (there are about 20)
[Open #314 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/314)

<a href='https://usersnappublic.s3.amazonaws.com/2019-03-28/18-09/cbf0d57e-a67a-4044-9696-a5c99da5cb63.png'>![Usersnap Feedback - none of the components I added appear in the sidebar (there are about 20)](https://usersnappublic.s3.amazonaws.com/2019-03-28/18-09/9411fa32-f55e-49cf-98df-3babee0fddf4.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-03-28/18-09/cbf0d57e-a67a-4044-9696-a5c99da5cb63.png'>Download original image</a>

**Browser**: Chrome 73 (Windows 10)
**Referer**: [https://participedia.xyz/case/5666](https://participedia.xyz/case/5666)
**Screen size**: 1280 x 720 **Browser size**: 1707 x 771

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@scottofletcher does adding components work if you do it one at a time? Or does adding components not work at all? Thanks.

**Comment by scottofletcher** [comment]
nope, just tried adding one case and it doesn't work

**Comment by scottofletcher** [comment]
Ohhhh, just found a bug but it's complicated. here goes: 

Martin created an entry on 'Sciencewise' on .net which was moved to XYZ by Lucy (with the intention of changing the username under 'First submitted by' later on). 
Then, today Martin entered an updated version of the Sciencewise entry onto XYZ. We decided to keep that one since 1) it contains changes, and 2) it saves us having to change the username on the other one. 
HOWEVER, Martin has been entering a number of other cases over the past few days, all of which are components of Sciencewise. When he was filling out the component field, he selected the case that Lucy transferred because he hadn't yet enter his updated version. Now, when I go to enter components into his Sciencewise entry, it won't let me because components can only have one parent. If you go to the component pages (like [this ](https://participedia.xyz/case/5693) one or [this](https://participedia.xyz/case/5695) one), you'll see that they still list Sciencewise (the one Lucy entered) as the parent despite the fact that I deleted ('hid') it.

**Comment by scottofletcher** [comment]
In short: we really need a way to delete cases, otherwise I'm going to have to go through and remove any links/hyperlinks to them and, in this case, to make sure they aren't selected as a component or parent. same thing goes for method - those that are 'hidden' are still listed under 'Process' if the user filled out the field before they were 'hidden' - and organizations - again, still there if the user selected them before they were 'hidden' under Organizing Entities
