### ISSUE TITLE
Usersnap Feedback - Literally just spent a full 30 minutes filling out the data form and now this...

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#775]
**Sender**: scottowenfletcher@gmail.com
**Comment**: Literally just spent a full 30 minutes filling out the data form and now this...
[Open #473 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/473)

<a href='https://usersnappublic.s3.amazonaws.com/2019-07-07/19-48/80f16c08-b700-499f-ab54-6db73eb4751d.png'>![Usersnap Feedback - Literally just spent a full 30 minutes filling out the data form and now this...](https://usersnappublic.s3.amazonaws.com/2019-07-07/19-48/e61da407-2ef8-4f28-a2a2-3709426d0c48.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-07-07/19-48/80f16c08-b700-499f-ab54-6db73eb4751d.png'>Download original image</a>

**Browser**: Chrome 75 (Windows 10)
**Referer**: [https://participedia.net/case/new?full=1](https://participedia.net/case/new?full=1)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 873

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
P1 bug

**Comment by ascott** [comment]
sorry to hear that @scottofletcher. do you have any other details about this? Were you uploading media as well as fields and text? unfortunately this is the catchall error message when the server doesn't pass errors in the correct format back to the browser, so we unfortunately don't know what went wrong. if you happen to have any other details i will try to reproduce this.

**Comment by scottofletcher** [comment]
I'm sorry if I came off a little short, I had just spent so much time on the gosh darn fields (and not even the narrative) that the error message was like a kick in the teeth!
I think I figured out what went wrong: the image was too large. the error message did come up, and I was stuck on the form, but the entry did actually get published (twice, since I tried to clear a few fields and press it again with no apparent (at the time) luck). both of the entries published despite the error message had the lead image removed. I started the entry from scratch and used a resized version of the same picture and, low and behold, it worked.

**Comment by ascott** [comment]
ok thanks for the details. sounds like using a smaller image fixed your issues. did you see an error message specific to the too-large-image?

**Comment by scottofletcher** [comment]
nope, just the 'Sorry, something went wrong' message. and it's weird that the entry still gets published when the 'sorry' message comes up - I think that's the cause of a lot of duplicate entries (ie. user did something that caused the error message, fixed it, pressed publish again, error message, fixed it, etc.)
