### ISSUE TITLE
Usersnap Feedback - This page needs design help. 

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#84]
**Sender**: jesi.carson@gmail.com
**Comment**: This page needs design help. Assign to me. 
[Open #98 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/98)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-18/23-59/1c805480-54eb-4bc1-8979-3404bd638df4.png'>![Usersnap Feedback - This page needs design help. Assign to me.](https://usersnappublic.s3.amazonaws.com/2017-08-18/23-59/bdd3b624-f68c-4b90-82ea-1629de027ce6.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-18/23-59/1c805480-54eb-4bc1-8979-3404bd638df4.png'>Download original image</a>

**Browser**: Chrome 59 (macOS Sierra)
**Referer**: [https://participedia.xyz/profile](https://participedia.xyz/profile)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
@dethe for Autho generated profiles like mine (from gmail) we should definitely not display users email as their username by default. 

Other things:
- email icon does nothing and is in a random place
- spacing and typographic hierarchy of user metadata is wonky
- grid and list view icons floating below invisible line of "authored content" , should look like homepage search with rule line 
- see older mockup of profile page with "edit profile" button rather than floating edit button

**Comment by jesicarson** [comment]
@dethe is there a way to move this out of usersnaps into frontend? does that make sense?

**Comment by dethe** [comment]
You can link a new frontend issue to this by including the URL, but there isn't a way to move them directly.

**Comment by jesicarson** [comment]
@dethe not critical for user testing

**Comment by andreadelrio** [comment]
We already redesigned this page.
