### ISSUE TITLE
Usersnap Feedback - Staging test for filter results text - I had a set of results for Arts, an[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#960]
**Sender**: jesi.carson@gmail.com
**Comment**: Staging test for filter results text - I had a set of results for Arts, and tried to add another filter, but the drop down menus won’t open. Bug.
[Open #654 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/654)

<a href='https://usersnappublic.s3.amazonaws.com/2019-12-28/18-47/8455087e-07f7-4b89-b874-f6bfbb505e67.png'>![Usersnap Feedback - Staging test for filter results text - I had a set of results for Arts, an(...)](https://usersnappublic.s3.amazonaws.com/2019-12-28/18-47/9533d70d-4884-422f-a02e-19a7c0daa2e9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-12-28/18-47/8455087e-07f7-4b89-b874-f6bfbb505e67.png'>Download original image</a>

**Browser**: Safari 13 (iOS)
**Referer**: [https://ppedia-stage.herokuapp.com/?selectedCategory=case&query=Women&general_issues=arts](https://ppedia-stage.herokuapp.com/?selectedCategory=case&query=Women&general_issues=arts)
**Screen size**: 320 x 568 **Browser size**: 320 x 454

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by zphingphong** [comment]
The bug is

All query parameter filter are in `shared-field-option.js`.
Now, if there are multiple query. The filtering logic happened in `handlebars-helpers.js@filterCollections()`.

And the error shows up because the query parameter `query` doesn't exist in `shared-field-option.js`.

To fix this I added a new item in the array for `query` to handle this line
in `shared-field-option.js`
`if ( sharedFieldOptions[keys[i]].includes(arr[x]) ) {`

https://github.com/participedia/api/tree/pan-960
